# Generated by Django 4.1.5 on 2023-02-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="energymonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_r", models.DecimalField(decimal_places=2, max_digits=5)),
                ("current_y", models.DecimalField(decimal_places=2, max_digits=5)),
                ("current_b", models.DecimalField(decimal_places=2, max_digits=5)),
                ("voltage_r", models.DecimalField(decimal_places=2, max_digits=5)),
                ("voltage_y", models.DecimalField(decimal_places=2, max_digits=5)),
                ("voltage_b", models.DecimalField(decimal_places=2, max_digits=5)),
                ("avg_current", models.DecimalField(decimal_places=2, max_digits=5)),
                ("avg_voltage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("power", models.DecimalField(decimal_places=2, max_digits=5)),
                ("day", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                ("hour", models.DecimalField(decimal_places=2, max_digits=5)),
                ("minute", models.DecimalField(decimal_places=2, max_digits=5)),
                ("second", models.DecimalField(decimal_places=2, max_digits=5)),
                ("microsecond", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
