# Generated by Django 4.1.5 on 2023-02-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energymonitor",
            name="day",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="energymonitor",
            name="month",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="energymonitor",
            name="year",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
